name: build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install git libxrandr
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Run tests
        run: |
          xmake --version
          xmake -y
      - if: matrix.os == 'ubuntu-latest'
        run: |
          cp -R res/ build/linux/x86_64/release/
      - if: matrix.os == 'macOS-latest'
        run: |
          cp -R res/ build/macosx/x86_64/release/
      - if: matrix.os == 'windows-latest'
        run: |
          copy res/ build/windows/x64/release/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
